Update ViolentMonkeyScript.user.js
Changed unsafeWindow declaration for Firefox so that it Chrome doesn't complain about "Uncaught TypeError: $ is not a function"